[schools.hkr]
name = "Högskolan Kristianstad"
domain = "hkr.se"
urls = [
    "https://schema.hkr.se",
    "https://kronox.hkr.se"
]

[schools.mau]
name = "Malmö universitet"
domain = "mau.se"
urls = [
    "https://schema.mau.se",
    "https://kronox.mau.se"
]

[schools.oru]
name = "Örebro universitet"
domain = "oru.se"
urls = [
    "https://schema.oru.se",
    "https://kronox.oru.se",
]

[schools.ltu]
name = "Luleå tekniska universitet"
domain = "ltu.se"
urls = [
    "https://schema.ltu.se",
]

[schools.hig]
name = "Högskolan i Gävle"
domain = "hig.se"
urls = [
    "https://schema.hig.se",
    "https://kronox.hig.se"
]

[schools.sh]
name = "Södertörns högskola"
domain = "sh.se"
urls = [
    "https://schema.sh.se",
    "https://kronox.sh.se",
]

[schools.hv]
name = "Högskolan Väst"
domain = "hv.se"
urls = [
    "https://schema.hv.se",
    "https://kronox.hv.se"
]

[schools.hb]
name = "Högskolan i Borås"
domain = "hb.se"
urls = [
    "https://schema.hb.se",
    "https://kronox.hb.se"
]

[schools.mdh]
name = "Mälardalens universitet"
domain = "mdh.se"
urls = [
    "https://schema.mdh.se",
    "https://webbschema.mdh.se"
]