// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with username and password across multiple school URLs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully authenticated",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or login failed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/validate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Check if a user session is valid across multiple school URLs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Validate user session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session validation result",
                        "schema": {
                            "$ref": "#/definitions/handlers.SessionValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Missing session_id in Authorization header",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error during validation",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}/cancel": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel an existing resource booking using booking ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Cancel booking by ID (alternative endpoint)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Booking ID to cancel",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Booking cancelled successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "bookingId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Confirm an existing resource booking with resource ID provided in request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Confirm booking with resource ID in body",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Booking ID to confirm",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Resource ID for confirmation",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfirmBookingBodyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Booking confirmed successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "bookingId path parameter or resourceId in body required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}/confirm/{resourceId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Confirm an existing resource booking using resource ID and booking ID from path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Confirm booking by ID (path parameters)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Booking ID to confirm",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID for confirmation",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Booking confirmed successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "bookingId or resourceId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all events for the authenticated user across multiple school URLs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get user events",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of user events",
                        "schema": {
                            "$ref": "#/definitions/handlers.EventsListResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/support/{participatorId}/{supportId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add support for a specific participator in an event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Add event support",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Participator ID to support",
                        "name": "participatorId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Support ID to add",
                        "name": "supportId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully added event support",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "participatorId or supportId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/register": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register the authenticated user for a specific event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Register for event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event ID to register for",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully registered for event",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "eventId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/support/{participatorId}/{supportId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove support for a specific participator in an event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Remove event support",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Participator ID",
                        "name": "participatorId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Support ID to remove",
                        "name": "supportId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully removed event support",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "eventId, participatorId, or supportId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/unregister": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Unregister the authenticated user from a specific event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Unregister from event",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event ID to unregister from",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully unregistered from event",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "eventId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/programmes/search": {
            "get": {
                "description": "Search for academic programmes across multiple school URLs using a search query",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "programmes"
                ],
                "summary": "Search for programmes",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"Computer Science\"",
                        "description": "Search query for programmes",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of programmes matching the search query",
                        "schema": {
                            "$ref": "#/definitions/handlers.ProgrammesResponse"
                        }
                    },
                    "400": {
                        "description": "Search query 'q' required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to fetch or parse programmes",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all available resources for booking across multiple school URLs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get all resources",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available resources",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResourcesListResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/availability": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get available time slots for a specific resource on a given date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get resource availability",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID to check availability for",
                        "name": "resource_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Available time slots for the resource",
                        "schema": {
                            "$ref": "#/definitions/handlers.AvailabilityResponse"
                        }
                    },
                    "400": {
                        "description": "resource_id and date are required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/bookings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all bookings made by the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get user bookings",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of user bookings",
                        "schema": {
                            "$ref": "#/definitions/handlers.BookingsListResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/bookings/{bookingId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel an existing resource booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Cancel a booking",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Booking ID to cancel",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Booking cancelled successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "bookingId is required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/bookings/{bookingId}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Confirm an existing resource booking with resource ID in request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Confirm a booking",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Booking ID to confirm",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Confirmation details",
                        "name": "confirmation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.ConfirmBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Booking confirmed successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/{resourceId}/availability": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get available time slots for a specific resource on a given date using path parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get available resources (alternative endpoint)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID to check availability for",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Available time slots for the resource",
                        "schema": {
                            "$ref": "#/definitions/handlers.AvailabilityResponse"
                        }
                    },
                    "400": {
                        "description": "resourceId and date are required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/{resourceId}/book": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new booking for a specific resource and time slot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Book a resource",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID to book",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Booking details",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.BookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Booking successful",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/{resourceId}/bookings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all active bookings for a specific resource",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get active bookings for resource",
                "parameters": [
                    {
                        "type": "string",
                        "format": "Bearer {session_id}",
                        "description": "Bearer token (session ID)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID to get bookings for",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of active bookings for the resource",
                        "schema": {
                            "$ref": "#/definitions/handlers.BookingsListResponse"
                        }
                    },
                    "400": {
                        "description": "resourceId path parameter required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session required",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "description": "Retrieve schedule events for one or more schedule IDs with optional language and date filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule events",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"schedule1,schedule2,schedule3\"",
                        "description": "Comma-separated list of schedule IDs",
                        "name": "schedule_ids",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"en\"",
                        "description": "Language preference for the schedule",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "example": "\"2024-01-15\"",
                        "description": "Start date for filtering events (YYYY-MM-DD format)",
                        "name": "start_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of schedule events",
                        "schema": {
                            "$ref": "#/definitions/handlers.ScheduleEventsResponse"
                        }
                    },
                    "400": {
                        "description": "Missing required parameters or invalid date format",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to fetch or parse schedule data",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "booking.Availability": {
            "type": "string",
            "enum": [
                "UNAVAILABLE",
                "AVAILABLE",
                "BOOKED"
            ],
            "x-enum-varnames": [
                "Unavailable",
                "Available",
                "Booked"
            ]
        },
        "booking.AvailabilitySlot": {
            "type": "object",
            "properties": {
                "availability": {
                    "$ref": "#/definitions/booking.Availability"
                },
                "location_id": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "time_slot_id": {
                    "type": "string"
                }
            }
        },
        "booking.Booking": {
            "type": "object",
            "properties": {
                "confirmation_closed": {
                    "type": "string"
                },
                "confirmation_open": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "resource_id": {
                    "type": "string"
                },
                "show_confirm_button": {
                    "type": "boolean"
                },
                "show_unbook_button": {
                    "type": "boolean"
                },
                "time_slot": {
                    "$ref": "#/definitions/booking.TimeSlot"
                }
            }
        },
        "booking.BookingRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "slot": {
                    "$ref": "#/definitions/booking.AvailabilitySlot"
                }
            }
        },
        "booking.ConfirmBookingRequest": {
            "type": "object",
            "properties": {
                "resourceId": {
                    "type": "string"
                }
            }
        },
        "booking.Resource": {
            "type": "object",
            "properties": {
                "availabilities": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "$ref": "#/definitions/booking.AvailabilitySlot"
                        }
                    }
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "time_slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/booking.TimeSlot"
                    }
                }
            }
        },
        "booking.TimeSlot": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "handlers.AvailabilityResponse": {
            "description": "Response containing available time slots",
            "type": "object",
            "properties": {
                "availability": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/booking.AvailabilitySlot"
                    }
                }
            }
        },
        "handlers.BookingsListResponse": {
            "description": "Response containing list of bookings",
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/booking.Booking"
                    }
                }
            }
        },
        "handlers.ConfirmBookingBodyRequest": {
            "description": "Request body for confirming a booking with resource ID",
            "type": "object",
            "required": [
                "resourceId"
            ],
            "properties": {
                "resourceId": {
                    "type": "string",
                    "example": "res_123"
                }
            }
        },
        "handlers.ErrorResponse": {
            "description": "Error response structure",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "handlers.EventsListResponse": {
            "description": "Response containing list of user events",
            "type": "object",
            "properties": {
                "events": {
                    "$ref": "#/definitions/parsers.EventsResponse"
                }
            }
        },
        "handlers.Programme": {
            "description": "Academic programme information",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "CS101"
                },
                "credits": {
                    "type": "integer",
                    "example": 180
                },
                "description": {
                    "type": "string",
                    "example": "Bachelor's degree in Computer Science"
                },
                "id": {
                    "type": "string",
                    "example": "prog_123"
                },
                "name": {
                    "type": "string",
                    "example": "Computer Science"
                }
            }
        },
        "handlers.ProgrammesResponse": {
            "description": "Response containing list of programmes matching the search criteria",
            "type": "object",
            "properties": {
                "programmes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Programme"
                    }
                }
            }
        },
        "handlers.ResourcesListResponse": {
            "description": "Response containing list of available resources",
            "type": "object",
            "properties": {
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/booking.Resource"
                    }
                }
            }
        },
        "handlers.ScheduleEvent": {
            "description": "Schedule event information",
            "type": "object",
            "properties": {
                "courseCode": {
                    "type": "string",
                    "example": "MATH101"
                },
                "endTime": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "evt_123"
                },
                "instructor": {
                    "type": "string",
                    "example": "Dr. Smith"
                },
                "location": {
                    "type": "string",
                    "example": "Room A101"
                },
                "startTime": {
                    "type": "string",
                    "example": "2024-01-15T09:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Math Lecture"
                }
            }
        },
        "handlers.ScheduleEventsResponse": {
            "description": "Response containing list of schedule events parsed from XML",
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ScheduleEvent"
                    }
                }
            }
        },
        "handlers.SessionValidationResponse": {
            "description": "Session validation response structure",
            "type": "object",
            "properties": {
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handlers.SuccessResponse": {
            "description": "Standard success response",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                }
            }
        },
        "parsers.EventsResponse": {
            "type": "object",
            "properties": {
                "registered": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.AvailableUserEvent"
                    }
                },
                "unregistered": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.AvailableUserEvent"
                    }
                },
                "upcoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.UpcomingUserEvent"
                    }
                }
            }
        },
        "user.AvailableUserEvent": {
            "type": "object",
            "properties": {
                "anonymous_code": {
                    "type": "string"
                },
                "event_end": {
                    "type": "string"
                },
                "event_start": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_registered": {
                    "type": "boolean"
                },
                "last_signup_date": {
                    "type": "string"
                },
                "participator_id": {
                    "type": "string"
                },
                "requires_choosing_location": {
                    "type": "boolean"
                },
                "support_available": {
                    "type": "boolean"
                },
                "support_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UpcomingUserEvent": {
            "type": "object",
            "properties": {
                "event_end": {
                    "type": "string"
                },
                "event_start": {
                    "type": "string"
                },
                "first_signup_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and session token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5055",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Kronox API",
	Description:      "A RESTful Web API for managing Kronox web resources, schedules, events, and bookings",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
